# Generated by Django 4.2.28 on 2026-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('image', models.URLField()),
                ('date', models.TextField()),
            ],
        ),
    ]
