# Generated by Django 4.2.28 on 2026-02-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='칼럼 아이디')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('title', models.CharField(max_length=255, verbose_name='칼럼 제목')),
                ('summary', models.TextField(verbose_name='본문 요약')),
                ('image', models.URLField(verbose_name='이미지 URL')),
                ('posted_at', models.DateField(verbose_name='발행 날짜')),
                ('url', models.URLField(verbose_name='원문 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
