# Generated by Django 4.2.28 on 2026-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='date',
            field=models.DateField(verbose_name='발행 날짜'),
        ),
        migrations.AlterField(
            model_name='column',
            name='identifier',
            field=models.CharField(max_length=255, unique=True, verbose_name='칼럼 아이디'),
        ),
        migrations.AlterField(
            model_name='column',
            name='image',
            field=models.URLField(verbose_name='칼럼 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='column',
            name='summary',
            field=models.TextField(verbose_name='칼럼 미리보기? 요약? 카드 밑에 나타나는 내용'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(max_length=255, verbose_name='칼럼 제목'),
        ),
        migrations.AlterModelTable(
            name='column',
            table='column',
        ),
    ]
